trigger:
- master

resources:
- repo: self

variables:
  imageName: 'firstrepo'
  imageTag: '$(Build.BuildId)'
  fullImageName: '$(imageName):$(imageTag)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
       name: New-agent
       vmImage: New-agent
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.txt'
        repository: '$(imageName)'         
        tags: |
          $(imageTag)                     

- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    pool:
       name: New-agent
       vmImage: New-agent
    steps:
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        containerRegistry: 'myhubpassword'  
        repository: '$(imageName)'          
        command: push
        tags: |
          $(imageTag)                      
