trigger:
- master

resources:
- repo: self

variables:
  dockerHubUsername: 'darshan30899'
  imageName: 'firstrepo'
  imageTag: '$(Build.BuildId)'
  fullImageName: '$(dockerHubUsername)/$(imageName):$(imageTag)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
       name: New-agent
       vmImage: New-agent
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
         command: build
         dockerfile: '$(Build.SourcesDirectory)/Dockerfile.txt'
         repository: '$(dockerHubUsername)/$(imageName)'  
         tags: |
              $(imageTag)                    

- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    pool:
       name: New-agent
       vmImage: New-agent
    steps:
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
          containerRegistry: 'myhubpassword'               
          repository: '$(dockerHubUsername)/$(imageName)'   
          command: push
          tags: |
            $(imageTag)
- stage: copyfiles
  displayName: copyfiles
  jobs:
  - job: copyfiles
    displayName: copyfiles
    pool:
       name: New-agent
       vmImage: New-agent
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(agent.builddirectory)'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
- stage: artifact
  displayName: artifact
  jobs:
  - job: artifact
    displayName: artifact
    pool:
       name: New-agent
       vmImage: New-agent
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'