trigger:
- master

resources:
- repo: self

variables:
  dockerHubUsername: 'darshan30899'
  imageName: 'firstrepo'
  imageTag: '$(Build.BuildId)'
  fullImageName: '$(dockerHubUsername)/$(imageName):$(imageTag)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
       name: New-agent
       vmImage: New-agent
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
         command: build
         dockerfile: '$(Build.SourcesDirectory)/Dockerfile.txt'
         repository: '$(dockerHubUsername)/$(imageName)'  
         tags: |
              $(imageTag)                    

- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    pool:
       name: New-agent
       vmImage: New-agent
    steps:
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
          containerRegistry: 'myhubpassword'               
          repository: '$(dockerHubUsername)/$(imageName)'   
          command: push
          tags: |
            $(imageTag)
- stage: copyfiles
  displayName: copyfiles
  jobs:
  - job: copyfiles
    pool:
      name: New-agent
    steps:
    - script: |
        echo "Source directory:"
        ls -R $(Build.SourcesDirectory)
      displayName: 'Debug: List source folder'
 
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
 
    - script: |
        echo "Artifact staging directory:"
        ls -R $(Build.ArtifactStagingDirectory)
      displayName: 'Debug: List artifact staging folder'
 
- stage: artifact
  displayName: artifact
  jobs:
  - job: artifact
    pool:
      name: New-agent
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'